Repository Warzone2100/warzone2100, pull requests merged in 2024-03, with the labels that each got.

#3673 Adjust skybox fog
  data/base/shaders/skybox.vert
  data/base/shaders/vk/skybox.vert
Labels: Enhancement

#3594 EMP bomb splash radius 2 to 3, long range 3 to 5
  data/mp/stats/weapons.json
Labels: Multiplayer/Skirmish, Balance

#3626 (MP)HRA cost rollback
  data/mp/stats/weapons.json
Labels: Multiplayer/Skirmish, Balance

#3707 Switch features to use `PagedEntityContainer<FEATURE>` as backing storage
  src/feature.cpp
  src/feature.h
  src/objmem.cpp
Labels: Enhancement

#3714 PagedEntityContainer: fix `advance_page_index()` for expired pages
  lib/framework/paged_entity_container.h
Labels: Bug

#3715 display3d.cpp: don't use heap allocation for `buildBlueprint()`
  src/display3d.cpp
  src/structure.cpp
  src/structure.h
Labels: Bug
